### ISSUE TITLE
Use more specific exception types

### ISSUE THREAD

**Issue by fdutton** [DmitrySoshnikov/syntax#38]
Disclaimer: I am not a PHP developer but I am writing a translator for our PHP team that converts a Sphinx search expression into an ElasticSearch search expression as part of their migration from Sphinx to ElasticSearch.

The PHP team has provided a little over 1000 unit tests. Some are positive tests and some are negative tests. An example negative test is mismatched parenthesis. What we would like to do is instruct PHPUnit to expect an exception in this case, however, PHPUnit does not allow expecting \Exception since the authors claim that it leads to unintended consequences. PHPUnit wants you to use something more concrete like SyntaxException or SemanticException.

It could be that I am misunderstanding what PHPUnit is requesting so I am open to correction. However, if I understand this correctly please use a more specific exception type.

**Comment by DmitrySoshnikov** [comment]
@fdutton, yeah, I was also thinking about this exact issue. And I also changed this for JS plugin -- it issues [SyntaxError](https://github.com/DmitrySoshnikov/syntax/blob/master/src/templates/lr.template.js#L211) instead of generic `Error` (fixed as part of https://github.com/DmitrySoshnikov/syntax/commit/b527c9c13793c3dd951a87bb5c32583d367d7b07).

I think a custom `SyntaxException` for PHP plugin makes sense. I'll appreciate a PR for this, or will get to it soon.

**Comment by DmitrySoshnikov** [comment]
Fixed by https://github.com/DmitrySoshnikov/syntax/commit/7ffd6fcf527cb2a3eac4fa41c2cd6abb010412f7.

Notice, there is an ability to provide namespace for PHP now using `--namespace 'MyNamespace'` option. Then the thrown exception will be `MyNamespace\SyntaxException` instead of just `SyntaxException`. Also a parser should be used via namespace in this case: `MyNamespace\MyParser::parse(...)`.
