### ISSUE TITLE
Consider using different tokens to delimit insertion points

### ISSUE THREAD

**Issue by fdutton** [DmitrySoshnikov/syntax#41]
The templates contain insertion points delimited by '<<' and '>>'. I have not delved into the code to see how this is handled but '<<' and '>>' represent reserved operators in several C-based languages (e.g., C, C++, C# and Java use '<<' to represent a left-shift). This could make it awkward to write a proper template.

Consider using something that is not already used by any language or framework. Most double character tokens are already used. For example:
* ```{{``` : Mustache
* ```[[```: PHP, Javascript, etc.
* ```@@```: I cannot remember

I recommend using ```{{{``` since I do not know of any language or framework using this particular delimiter.

**Comment by DmitrySoshnikov** [comment]
Yeah, this may break code highlighting in text-editors, but technically works. Currently it's just simple string replace for specific template variables. E.g. [in PHP plugin](https://github.com/DmitrySoshnikov/syntax/blob/master/src/plugins/php/php-parser-generator-trait.js#L33) trait.

Usually class hierarchy which handles templates in code generation is:

[LRParserGenerator#PluginName#](https://github.com/DmitrySoshnikov/syntax/blob/master/src/plugins/php/lr/lr-parser-generator-php.js) < [GenericPluginTraitFor_LL_and_LR](https://github.com/DmitrySoshnikov/syntax/blob/master/src/plugins/php/php-parser-generator-trait.js) < [LRParserGeneratorDefault](https://github.com/DmitrySoshnikov/syntax/blob/master/src/lr/lr-parser-generator-default.js) < [BaseParserGenerator](https://github.com/DmitrySoshnikov/syntax/blob/master/src/base-parser-generator.js).

All these define methods which handle specific template `<<...>>` vars. And child sub-classes, or traits may override some methods or provide custom methods for custom templates vars for a specific plugin.

If it's desirable to have custom template vars delimiters, instead of hardcoded `<<...>>` we can provide either instance variables on the class:

```js
// Default template delimiters.
this.tmplLeft = '<<';
this.tmplRight = '>>';
```

Child classes then can override.

It can also be a method:

```js
// Default implementation, plugins can override.
getTemplateVarDelimiters() {
  return ['<<', '>>'];
}
```

Then all [replaces](https://github.com/DmitrySoshnikov/syntax/blob/master/src/plugins/php/php-parser-generator-trait.js#L33) should be done as just:

```js
this.writeData(
  'TABLE',
  this._toPHPArray(this.generateParseTableData()),
);
```

And we can fix the [writeData](https://github.com/DmitrySoshnikov/syntax/blob/master/src/base-parser-generator.js#L161) itself to append the delimiters.

**Comment by DmitrySoshnikov** [comment]
Fixed in https://github.com/DmitrySoshnikov/syntax/commit/2cb2987ebed8b2d54bf1218c763c7fbc5080a1ad.
