### ISSUE TITLE
Latest build not working

### ISSUE THREAD

**Issue by DewaldDeJager** [DmitrySoshnikov/syntax#45]
Hello,

I have just cloned the repo, run `npm install` and `npm run build` which both executed successfully. However, when I run the utility with `./bin/syntax` it gives me the following output:

```
[syntax-master]$ ./bin/syntax --help
syntax-master/bin/syntax:196
            const [reducePart, shiftPart] = table.splitSRParts(conflict);
                  ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

I am running Node v5.3.0 on Fedora 24 x64.

**Comment by DmitrySoshnikov** [comment]
Hi,

Thanks for the report, it's fixed in for `./bin/syntax` in https://github.com/DmitrySoshnikov/syntax/commit/df41656dec0f58355d337ed14b647ec11676b204 (and in `0.0.86`, so executable `syntax-cli` from npm would work in Node 5).

However, a recommended version of Node is `6.*`. If for development, some tests will fail in Node `5.*` because of syntax errors, since use Node features which are available only since version 6. We can open a separate issue to make tests wok in Node 5, if upgrading to Node 6 is not easy on your server.

**Comment by DmitrySoshnikov** [comment]
FYI: tests should pass in Node `5.*` after https://github.com/DmitrySoshnikov/syntax/commit/0f8b0ad127836f1d0fb60f0f427b04c1bd26ed29, however a recommended version of Node for development is still `6.*`.

**Comment by DewaldDeJager** [comment]
I have tested in both Node v5.3.0 and v6.10.1 and it is working now. Thank you Dmitry!
